apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: readyhat-gif2stream
    app.kubernetes.io/component: gifstream-producer
    app.kubernetes.io/instance: gif2stream
    app.kubernetes.io/name: readyhat-gif2stream
    app.kubernetes.io/part-of: gifstream
    app.openshift.io/runtime: nodejs
  name: readyhat-gif2stream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readyhat-gif2stream
  template:
    metadata:
      labels:
        app: readyhat-gif2stream
    spec:
      containers:
      - name: readyhat-gif2tream
        imagePullPolicy: Always
        image: quay.io/readyhat/gif2stream:latest
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 1337
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 1337
          protocol: TCP
        # - containerPort: 8443
        #   protocol: TCP
        # - containerPort: 8778
        #   protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 1337
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
